# Generated by Django 3.2 on 2021-05-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='currentSection',
            field=models.CharField(blank=True, choices=[('customerInfoMin', 'customerInfoMin'), ('lovedOnes', 'lovedOnes'), ('creditInfo', 'creditInfo'), ('incomeExpenseSvgs', 'incomeExpenseSvgs'), ('detailedIncome', 'detailedIncome'), ('detailedExpense', 'detailedExpense'), ('detailedSavings', 'detailedSavings'), ('otherInsCoverage', 'otherInsCoverage'), ('personalPresentment', 'personalPresentment')], max_length=40, null=True, verbose_name='Discussion Section'),
        ),
    ]
