# Generated by Django 3.2 on 2022-06-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0002_auto_20220610_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='applicantId',
            field=models.CharField(blank=True, help_text='Applicant ID', max_length=100, null=True, verbose_name='Applicant ID'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='application_number',
            field=models.CharField(blank=True, help_text='Application Number', max_length=100, null=True, verbose_name='Application Number'),
        ),
    ]
