# Generated by Django 3.2 on 2021-05-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0002_insurancediscussion_currentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancediscussion',
            name='primaryAge',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Age'),
        ),
    ]
