# Generated by Django 3.2 on 2022-06-21 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0002_auto_20220610_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancediscussion',
            name='sssavingsEmergencyFund',
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='hppCreditLmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='HPP Credit Limit'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='hppMaxRebalancingLmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='HPP Re-balancing Limit'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='isJoint',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=2, null=True, verbose_name='Joint application'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='loanAmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Loan Amount'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='loanClassNumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='Loan Class Number'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='loanPmtAmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Loan Payment Amount'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='loanPmtFrequency',
            field=models.CharField(blank=True, choices=[('m', 'Monthly'), ('bm', 'Bi-Monthly'), ('w', 'Weekly'), ('sw', 'Semi-Weekly')], max_length=2, null=True, verbose_name='Mortgage Payment Frequency'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='mortgageCLassNumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mortgage Class Number'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='mortgageNumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mortgage Number'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='plcCLassNumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='PLC Class Number'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='plcCreditLmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PLC Credit Limit'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='plcInterestRate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='PLC Interest Rates'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='plcMMortgageNumber',
            field=models.CharField(blank=True, max_length=50, verbose_name='PLC mMortgage Number'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='plcRepaymentType',
            field=models.CharField(blank=True, max_length=50, verbose_name='PLC repayment Type'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='preProcessData',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='preProcessData', to='insuranceProducts.insurancepreprocessdata'),
            preserve_default=False,
        ),
    ]
