# Generated by Django 3.2 on 2022-06-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0002_auto_20220610_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitSurveyMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('exit_id', models.CharField(help_text='Exit ID', max_length=11, unique=True, verbose_name='Exit ID')),
                ('exit_selector', models.CharField(help_text='Exit Selector', max_length=100, unique=True, verbose_name='Exit Selector')),
                ('exit_msg', models.CharField(help_text='Exit Message', max_length=500, verbose_name='Exit Msg')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
