# Generated by Django 3.2 on 2022-05-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0002_auto_20220523_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='product_cibc_code',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
