# Generated by Django 3.2 on 2022-05-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0003_insuranceproduct_product_cibc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
