# Generated by Django 3.2 on 2022-06-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0003_auto_20220621_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='primaryPreferredName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Preferred Name'),
        ),
    ]
