# Generated by Django 3.2 on 2021-05-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0003_alter_insurancediscussion_primaryage'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='coGender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=2, null=True, verbose_name='Co Borrower - Gender'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='primaryGender',
            field=models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Other')], max_length=2, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='agentOverallPerceptionOfCustomerResp',
            field=models.CharField(blank=True, choices=[('positive', 'positive'), ('neutral', 'neutral'), ('negative', 'negative')], max_length=20, null=True, verbose_name='Agent Perception of customer response'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='canada_provence',
            field=models.CharField(blank=True, choices=[('nl', 'Newfoundland and Labrador'), ('pw', 'Prince Edward Island'), ('ns', 'Nova Scotia'), ('nb', 'New Brunswick'), ('qc', 'Quebec'), ('on', 'Ontario'), ('mb', 'Manitoba'), ('sk', 'Saskatchewan'), ('ab', 'Alberta'), ('bc', 'British Columbia'), ('yt', 'Yukon'), ('nt', 'Northwest Territories'), ('nu', 'Nunavut')], max_length=2, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='coFirstName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Co Borrower - First Name'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='coLastName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Co Borrower - Last Name'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='coMiddleName',
            field=models.CharField(blank=True, max_length=50, verbose_name='Co Borrower - Middle Name'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='discussionOutcomes',
            field=models.CharField(blank=True, choices=[('declined', 'declined'), ('acceptedOffer', 'acceptedOffer'), ('requiresFollowup', 'requiresFollowup')], max_length=20, null=True, verbose_name='Outcome of discussion'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='hasChildrenFinResponsibility',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=2, null=True, verbose_name='Children Financial Responsibility'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='hasOthersFinResponsibility',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=2, null=True, verbose_name='Other Financial Responsibility'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='hasParentsFinResponsibility',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=2, null=True, verbose_name='Other Relatives Financial Responsibility'),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='hasPartnerFinResponsibility',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=2, null=True, verbose_name='Partner Financial Responsibility'),
        ),
    ]
