# Generated by Django 3.2 on 2022-06-17 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0003_auto_20220617_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancediscussion',
            name='applicantId',
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='application_status',
            field=models.CharField(choices=[('inprocess', 'INPROCESS'), ('complete', 'COMPLETE'), ('incomplete', 'INCOMPLETE')], default='inprocess', max_length=10),
        ),
        migrations.CreateModel(
            name='InsuranceDiscussionApplicantDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=300, null=True)),
                ('application_number', models.CharField(help_text='Application Number', max_length=100, verbose_name='Application Number')),
                ('applicantID', models.CharField(help_text='Applicant ID', max_length=100, verbose_name='Applicant ID')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('insDiscussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insuranceProducts.insurancediscussion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
