# Generated by Django 3.2 on 2022-05-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0004_insuranceproduct_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvinceResidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('province', models.CharField(help_text='Province', max_length=3, verbose_name='Province')),
                ('description', models.CharField(help_text='Province Description', max_length=100, verbose_name='Province Description')),
                ('residency', models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No')], max_length=2, null=True, verbose_name='Canadian Residency')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Province Residence Master',
                'db_table': 'province_residence_master',
            },
        ),
    ]
