# Generated by Django 3.2 on 2022-06-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0004_auto_20220617_1640'),
        ('insuranceProducts', '0004_auto_20220622_1230'),
    ]

    operations = [
    ]
