# Generated by Django 3.2 on 2022-06-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0004_insurancediscussion_primarypreferredname'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='primaryEmail',
            field=models.CharField(blank=True, max_length=50, verbose_name='Email'),
        ),
    ]
