# Generated by Django 3.2 on 2022-04-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0004_auto_20210519_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancediscussion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
