# Generated by Django 3.2 on 2022-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0005_merge_0004_auto_20220617_1640_0004_auto_20220622_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitsurveymaster',
            name='exit_radio_disply',
            field=models.CharField(blank=True, help_text='Radio Message', max_length=500, verbose_name='Radio Msg'),
        ),
    ]
