# Generated by Django 3.2 on 2022-06-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0005_insurancediscussion_primaryemail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancediscussion',
            old_name='canada_provence',
            new_name='canada_province',
        ),
    ]
