# Generated by Django 3.2 on 2022-06-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0006_exitsurveymaster_exit_radio_disply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exitsurveymaster',
            old_name='exit_radio_disply',
            new_name='exit_radio_display',
        ),
    ]
