# Generated by Django 3.2 on 2022-05-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0006_alter_insuranceeligibility_residency'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('occupation_code', models.CharField(help_text='Occupation Code', max_length=10, verbose_name='Occupation Code')),
                ('occupation_name', models.CharField(help_text='Occupation Name', max_length=100, verbose_name='Occupation Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name_plural': 'Occupation Master',
                'db_table': 'occupation_master',
            },
        ),
    ]
