# Generated by Django 3.2 on 2022-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0006_alter_insurancediscussion_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='approxNetIncome',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Approximate Net Income'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='currentApplicationPmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Current Application Payment'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='savingsEmergencyFund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Saving & Emergency Fund'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='totalExistingDebt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Existing Debt'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='totalMonthlyPmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Monthly Payment'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='totalSecuredAmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Secured Amount'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='totalUnsecuredAmt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Total Unsecured Amount'),
        ),
    ]
