# Generated by Django 3.2 on 2022-06-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0006_rename_canada_provence_insurancediscussion_canada_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancediscussion',
            old_name='mortgagePmtAmount',
            new_name='mortgagePmtAmt',
        ),
    ]
