# Generated by Django 3.2 on 2022-05-25 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0007_occupationmaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceeligibility',
            name='military',
        ),
        migrations.AddField(
            model_name='insuranceeligibility',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='insuranceProducts.occupationmaster'),
        ),
    ]
