# Generated by Django 3.2 on 2022-06-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0007_rename_mortgagepmtamount_insurancediscussion_mortgagepmtamt'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='coApplicantId',
            field=models.CharField(blank=True, max_length=50, verbose_name='Co Applicant Id'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='primaryApplicantId',
            field=models.CharField(blank=True, max_length=50, verbose_name='Primary Applicant Id'),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='status',
            field=models.CharField(blank=True, max_length=10, verbose_name='Current Status'),
        ),
    ]
