# Generated by Django 3.2 on 2022-05-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0007_auto_20220510_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancediscussion',
            name='sssavingsEmergencyFund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Saving & Emergency Fund'),
        ),
    ]
