# Generated by Django 3.2 on 2022-06-27 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0007_rename_exit_radio_disply_exitsurveymaster_exit_radio_display'),
        ('insuranceProducts', '0008_auto_20220624_1225'),
    ]

    operations = [
    ]
