# Generated by Django 3.2 on 2022-05-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0008_auto_20220525_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provinceresidence',
            name='residency',
            field=models.CharField(blank=True, choices=[('Canada', 'Canadian Residence'), ('Other', 'Others')], max_length=50, null=True, verbose_name='Residency'),
        ),
    ]
