# Generated by Django 3.2 on 2022-06-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0009_merge_20220627_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancediscussion',
            name='coApplicantId',
        ),
        migrations.RemoveField(
            model_name='insurancediscussion',
            name='preProcessData',
        ),
        migrations.RemoveField(
            model_name='insurancediscussion',
            name='primaryApplicantId',
        ),
        migrations.RemoveField(
            model_name='insurancediscussion',
            name='status',
        ),
        migrations.RemoveField(
            model_name='insurancediscussionapplicantdetails',
            name='active',
        ),
        migrations.AddField(
            model_name='insurancediscussionapplicantdetails',
            name='type',
            field=models.CharField(choices=[('primary', 'PRIMARY APPLICANT'), ('co', 'CO-APPLICANT')], default='primary', max_length=10),
        ),
        migrations.AlterField(
            model_name='insurancediscussion',
            name='application_status',
            field=models.CharField(choices=[('complete', 'COMPLETE'), ('incomplete', 'INCOMPLETE')], default='inprocess', max_length=10),
        ),
    ]
