# Generated by Django 3.2 on 2022-05-30 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0010_insurancenoneligiblecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(help_text='Client ID', max_length=11, unique=True, verbose_name='Client ID')),
                ('client_name', models.CharField(help_text='Client Name', max_length=100, verbose_name='Client Name')),
                ('client_email', models.CharField(help_text='Client Email', max_length=100, verbose_name='Client Email')),
                ('client_phone', models.CharField(help_text='Client Phone', max_length=100, verbose_name='Client Phone')),
                ('effective_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effective Start Date')),
                ('effective_end_date', models.DateField(default='2099-12-31', verbose_name='Effective End Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
