# Generated by Django 3.2 on 2022-05-31 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0011_clientdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancecreditproduct',
            name='test',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
