# Generated by Django 3.2 on 2022-05-31 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0012_insurancecreditproduct_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancecreditproduct',
            name='test',
        ),
    ]
