# Generated by Django 3.2 on 2022-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0014_alter_insurancecreditproduct_credit_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetails',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientdetails',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dumpdata',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='dumpdata',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurancecreditproduct',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurancecreditproduct',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurancediscussion',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceeligibility',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceeligibility',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurancenoneligiblecontent',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insurancenoneligiblecontent',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='occupationmaster',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='occupationmaster',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provinceresidence',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='provinceresidence',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
