# Generated by Django 3.2 on 2022-06-02 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0014_alter_insurancecreditproduct_credit_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestionnaireMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.CharField(help_text='Assessment ID', max_length=11, unique=True, verbose_name='Assessment ID')),
                ('assessment_details', models.TextField(verbose_name='Non Assessment Details')),
                ('effective_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Effective Start Date')),
                ('effective_end_date', models.DateField(default='2099-12-31', verbose_name='Effective End Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
