# Generated by Django 3.2 on 2022-06-01 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0018_rename_insurancecreditproduct_insurancecreditproduct1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InsuranceCreditProduct1',
            new_name='InsuranceCreditProduct',
        ),
        migrations.AlterModelOptions(
            name='insurancecreditproduct',
            options={},
        ),
        migrations.AlterModelTable(
            name='insurancecreditproduct',
            table=None,
        ),
    ]
