# Generated by Django 3.2 on 2022-06-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0020_auto_20220601_1849'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsuranceCreditProduct1',
        ),
    ]
