# Generated by Django 3.2 on 2022-06-01 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0022_insurancecreditproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='creditProduct_code',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditProduct_code', to='insuranceProducts.insurancecreditproduct'),
        ),
    ]
