# Generated by Django 3.2 on 2022-06-02 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0023_insuranceproduct_creditproduct_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insurancecreditproduct',
            options={'verbose_name_plural': 'Insurance Credit Products Master'},
        ),
        migrations.AlterModelOptions(
            name='insuranceproduct',
            options={'verbose_name_plural': 'Insurance Products Master'},
        ),
        migrations.AlterModelTable(
            name='insurancecreditproduct',
            table='insurance_credit_products',
        ),
        migrations.AlterModelTable(
            name='insuranceproduct',
            table='insurance_products',
        ),
    ]
