# Generated by Django 3.2 on 2022-06-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0025_auto_20220606_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insuranceproduct',
            options={},
        ),
        migrations.AlterModelTable(
            name='insuranceproduct',
            table=None,
        ),
    ]
