# Generated by Django 3.2 on 2022-06-08 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0015_assessmentquestionnairemaster'),
        ('insuranceProducts', '0026_auto_20220606_1508'),
    ]

    operations = [
    ]
