# Generated by Django 3.2 on 2022-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0027_merge_20220608_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancediscussion',
            name='sssavingsEmergencyFund',
        ),
        migrations.AddField(
            model_name='assessmentquestionnairemaster',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='assessmentquestionnairemaster',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
