# Generated by Django 3.2 on 2022-06-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insuranceProducts', '0016_auto_20220608_1310'),
        ('insuranceProducts', '0028_auto_20220608_1908'),
    ]

    operations = [
    ]
