# Generated by Django 3.2 on 2021-05-20 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='clotheType',
            field=models.CharField(blank=True, choices=[('BlazerShirt', 'BlazerShirt'), ('BlazerSweater', 'BlazerSweater'), ('CollarSweater', 'CollarSweater'), ('Colors', 'Colors'), ('GraphicShirt', 'GraphicShirt'), ('Graphics', 'Graphics'), ('Hoodie', 'Hoodie'), ('ShirtVNeck', 'ShirtVNeck'), ('ShirtCrewNeck', 'ShirtCrewNeck'), ('ShirtScoopNeck', 'ShirtScoopNeck')], max_length=50, null=True, verbose_name='👔 Clothes'),
        ),
        migrations.AlterField(
            model_name='character',
            name='mouthType',
            field=models.CharField(blank=True, choices=[('Default', 'Default'), ('Concerned', 'Concerned'), ('Disbelief', 'Disbelief'), ('Eating', 'Eating'), ('Grimace', 'Grimace'), ('Sad', 'Sad'), ('ScreamOpen', 'ScreamOpen'), ('Serious', 'Serious'), ('Smile', 'Smile'), ('Tongue', 'Tongue'), ('Twinkle', 'Twinkle'), ('Vomit', 'Vomit')], max_length=50, null=True, verbose_name='👄 Mouth'),
        ),
    ]
