# Generated by Django 3.2 on 2022-05-04 07:43

from django.db import migrations
import django.db.models.deletion
import river.models.fields.state


class Migration(migrations.Migration):

    dependencies = [
        ('river', '0002_auto_20220504_1313'),
        ('stories', '0002_auto_20210519_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='objection',
            name='my_state_field',
            field=river.models.fields.state.StateField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='river.state'),
        ),
    ]
