# Generated by Django 3.2 on 2022-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_objection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandle',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandle',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandlestatstracker',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandlestatstracker',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objectioonstatstracker',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='objectioonstatstracker',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storycharacter',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storycharacter',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storystatstracker',
            name='created_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='storystatstracker',
            name='modified_by',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
