# Generated by Django 3.2 on 2022-06-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20220601_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objection',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objection',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objection',
            name='status',
            field=models.CharField(blank=True, choices=[('d', 'Draft'), ('ap', 'Approved'), ('re', 'Rejected')], default='d', max_length=5, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='objectionhandle',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objectionhandle',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objectionhandlestatstracker',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objectionhandlestatstracker',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objectioonstatstracker',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='objectioonstatstracker',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storycharacter',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storycharacter',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storystatstracker',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='storystatstracker',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
