# Generated by Django 3.2 on 2022-06-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20220606_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Open'), ('ap', 'Approved'), ('re', 'Rejected'), ('cl', 'Close')], default='d', max_length=5, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='objection',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Open'), ('ap', 'Approved'), ('re', 'Rejected'), ('cl', 'Close')], default='o', max_length=5, null=True, verbose_name='Status'),
        ),
    ]
