# Generated by Django 3.2 on 2022-06-10 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20220610_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='character',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='objection',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='objection',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='objectionhandle',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='objectionhandle',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='objectionhandlestatstracker',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='objectionhandlestatstracker',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='objectioonstatstracker',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='objectioonstatstracker',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='story',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='story',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='storycharacter',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storycharacter',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='storystatstracker',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='storystatstracker',
            name='modified_by',
        ),
    ]
