# Generated by Django 3.2 on 2022-06-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_auto_20220610_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objection',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandle',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandle',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandlestatstracker',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objectionhandlestatstracker',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objectioonstatstracker',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='objectioonstatstracker',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='storycharacter',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='storycharacter',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='storystatstracker',
            name='created_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='storystatstracker',
            name='modified_by',
            field=models.CharField(blank=True, editable=False, max_length=300, null=True),
        ),
    ]
